apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-pro
  namespace: kube-ops
spec:
  template:
    metadata:
      labels:
        app: nginx-pro
    spec:
      containers:
      - image: 192.168.56.12/k8s-ops/nginx_pro:${build_tag}
        imagePullPolicy: IfNotPresent
        name: nginx
