apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-pro
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: nginx-pro
    spec:
      containers:
      - image: 192.168.56.12/k8s-ops/nginx_pro:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: nginx
        env:
        - name: branch
          value: <BRANCH_NAME>
